### PR TITLE
fix Mesh::divideCol

### PR DESCRIPTION
**Pull request by wasawi**
Hello, 
divideCol didn't work for me. I got a crash when trying to divide the mesh vertically.
Please check out this fix.

Best,
J

### CODE REVIEW

**Comment by nariakiiwatani** [comment]
Thank you!

I couldn't reproduce the crash.
Could you tell me about your situation?

and, I guess your code and mine do the same.
How do you think why the crash occurs?

I want to see your stack trace for debugging.

**Comment by wasawi** [comment]
I'm on Visual Studio 2015.
I get this crash if I try to divide the mesh vertically:

```
>	example_debug.exe!std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator+=(__int64 _Off) Line 165	C++
 	example_debug.exe!std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator+=(__int64 _Off) Line 368	C++
 	example_debug.exe!std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator+(__int64 _Off) Line 374	C++
 	example_debug.exe!ofx::MeshWarp::Mesh::divideCol(int pos, float ratio) Line 51	C++
 	example_debug.exe!ofx::MeshWarp::Editor::DivideController::mousePressed(ofMouseEventArgs & args) Line 386	C++
 	example_debug.exe!ofx::MeshWarp::Editor::ManagedController::mousePressed(ofMouseEventArgs & args) Line 67	C++
 	example_debug.exe!ofEvent<ofMouseEventArgs,std::recursive_mutex>::make_function::__l2::<lambda>(const void * __formal, ofMouseEventArgs & t) Line 480	C++

```

Output:
`Expression: vector iterator + offset out of range`

**Comment by nariakiiwatani** [comment]
I see.
The debugger crashes due to a out-of-bounds iterator even if it weren't used.
Could you check my code? 
https://github.com/nariakiiwatani/ofxMeshWarp/tree/hotfix-divideCol

**Comment by wasawi** [comment]
I just tried it and it still crashes:

```
>	example_debug.exe!std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator+=(__int64 _Off) Line 165	C++
 	example_debug.exe!std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator+=(__int64 _Off) Line 368	C++
 	example_debug.exe!std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator+(__int64 _Off) Line 374	C++
 	example_debug.exe!ofx::MeshWarp::Mesh::divideCol(int pos, float ratio) Line 51	C++
 	example_debug.exe!ofx::MeshWarp::Editor::DivideController::mousePressed(ofMouseEventArgs & args) Line 386	C++
 	example_debug.exe!ofx::MeshWarp::Editor::ManagedController::mousePressed(ofMouseEventArgs & args) Line 67	C++
 	example_debug.exe!ofEvent<ofMouseEventArgs,std::recursive_mutex>::make_function::__l2::<lambda>(const void * __formal, ofMouseEventArgs & t) Line 480	C++

```

**Comment by wasawi** [comment]
Sorry i forgot to say I'm running OF 0.10.0

**Comment by wasawi** [comment]
Wops! sorry i don't know how did i test the fix the other day but probably i didn't clean my project before building again. 

Well anyways, your fix runs well. Only issue is that the branch has to be merged into master in order to keep the updates to OF 0.1.0.

Thank you!

**Comment by wasawi** [comment]
I will close the PR

**Comment by nariakiiwatani** [comment]
Thank you for reporting!
I added the fix to master.

**Pull request closed without merging**
